#Login Data
USERNAME = "OpencartPythonSet2"
#KEY = "PutiLKEL0Okx7GunisOutqZ65FwKVONJ10fS8Uoo1zaSv788N6iyalwSGfNPloCIKRtsAhGfJlYg8NW624uTnCOm42jtjeZyVNpnGxXcBOJ5G5kj4swirBebhSUTFJJnZo3XuLxFLZJuinqFqGXhjhYtEqRflTUjmSgnYkct5o366klCEN83TAHTV4Dm6q7Oyvja1UPJNQZYMp8rGidXS1j4VtRsLnoUdCnrz4IDBTfT23Kzw0gMjjkNuSCkhVPT"
KEY = "KbBa2RRD7bN6IADCt8pqggFw7P5Y5UWHWeQpRSzXrRow44YilXHdyUnQPCIdfWQ2MT4ykYpiSdycFfzH6ynMCRXzJL73TgqUex1TyrlIz8IuslRpHWQUNoEnXHN6lKFuzdYjseUKgOx6uPtipdaMHdLT6O7HYFo4YOaKnnCyGv0iNI1DUt2sX2J3gTLNEaw6DiucZgjkJOyhUaTU6tmk8haIx1nmWciGALNae81EH3muDmXiB7QADYGmY5NW1QQg"

#URL Data
BASE_URL = "http://localhost/OpenCart/"
LOGIN_URL = "index.php?route=api/login"
CHANGE_CURRENCY_URL = "index.php?route=api/currency"
ADD_TO_CART_URL = "index.php?route=api/cart/add"
EDIT_CART_PRODUCT_QUANTITY_URL = "index.php?route=api/cart/edit"
REMOVE_CART_PRODUCT_URL = "index.php?route=api/cart/remove"
DISPLAY_CART_PRODUCTS_URL = "index.php?route=api/cart/products"
APPLY_COUPON_URL = "index.php?route=api/coupon"
SET_CUSTOMER_URL = "index.php?route=api/customer"
APPLY_VOUCHER_URL = "index.php?route=api/voucher"
ADD_VOUCHER_URL = "index.php?route=api/voucher/add"
SET_SHIPPING_ADDRESS_URL = "index.php?route=api/shipping/address"
AVAILABLE_SHIPPING_METHODS_URL = "index.php?route=api/shipping/methods"
SET_SHIPPING_METHOD_URL = "index.php?route=api/shipping/method"
REWARD_URL = "index.php?route=api/reward"
MAXIMUM_REWARD_URL = "index.php?route=api/reward/maximum"
AVAILABLE_REWARD_URL = "index.php?route=api/reward/avaliable"
NEW_ORDER_URL = "index.php?route=api/order/add"
EDIT_ORDER_URL = "index.php?route=api/order/edit"
DELETE_ORDER_URL = "index.php?route=api/order/delete"
ORDER_INFO_URL = "index.php?route=api/order/info"
ORDER_HISTORY_URL = "index.php?route=api/order/history"
SET_PAYMENT_ADDRESS_URL = "index.php?route=api/payment/address"
AVAILABLE_PAYMENT_METHODS_URL = "index.php?route=api/payment/address"
SET_PAYMENT_METHOD_URL = "index.php?route=api/payment/method"